INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (1, 'RAFAEL CHAVEZ', TO_DATE('07 May 1990'));
INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (2, 'SOFIA CONTRERAS', TO_DATE('07 Jan 1990'));
INSERT INTO ROLE (ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'USER');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'ROLE_COMMON');
INSERT INTO USER (ID, EMAIL, FIRST_NAME, LAST_NAME, MOBILE, PASSWORD, USERNAME) VALUES (1, 'rchavez@itexico.com', 'Rafael', 'Chavez', '+1-415-555-5141', '$2a$10$IC7dStKzxssHEffAH7Yjlu24.WKlKk4cNAJIUKjRPFpCH0JwUt/Xq', 'rafa');
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (1, 1);