INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (1, 'RAFAEL CHAVEZ', TO_DATE('07 May 1990'));
INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (2, 'SOFIA CONTRERAS', TO_DATE('07 Jan 1990'));
